CREATE DATABASE `meshnote`;
USE `meshnote`;

CREATE TABLE IF NOT EXISTS `user`(
   `id` INT UNSIGNED AUTO_INCREMENT UNIQUE,
   `name` VARCHAR(255) NOT NULL,
   `password` VARCHAR(63) NOT NULL,
   PRIMARY KEY(`id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `tree`(
   `id` INT UNSIGNED AUTO_INCREMENT UNIQUE,
   `name` VARCHAR(255) NOT NULL,
   `type` INT NOT NULL,
   `filename` VARCHAR(255) NOT NULL,
   `filesize` INT NOT NULL,
   `parent` INT NOT NULL,
   `uptime` VARCHAR(255) NOT NULL,
   PRIMARY KEY(`id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `diary`(
   `id` INT UNSIGNED AUTO_INCREMENT UNIQUE,
   `user` INT NOT NULL,
   `year` INT NOT NULL,
   `month` INT NOT NULL,
   `day` INT NOT NULL,
   `count` INT NOT NULL,
   PRIMARY KEY(`id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;